# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches:
      - master
      - 'merge_grids'
      - 'grid-debug'
  pull_request:
    branches:
      - master
      - 'hobuinc/hexer'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
          miniconda-version: "latest"
          activate-environment: test
    - name: Bash
      shell: bash
      run: |
        pip install GDAL==3.2.3
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: mkdir build && cd build && cmake .. -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
   
    - name: Build
      # Build your program with the given configuration
      run: cd build && make

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ./pathstest
        ./gridtest

